with open('numar.txt','r') as f:
    n=f.readline()
    x='1*'+n+'='+str(1*int(n))
    y='2*'+n+'='+str(2*int(n))
    z='3*'+n+'='+str(3*int(n))
    a='4*'+n+'='+str(4*int(n))
    b='5*'+n+'='+str(5*int(n))
    c='6*'+n+'='+str(6*int(n))
    d='7*'+n+'='+str(7*int(n))
    e='8*'+n+'='+str(8*int(n))
    u='9*'+n+'='+str(9*int(n))
    g='10*'+n+'='+str(10*int(n))
with open('inmultire.txt','w') as f:
    f.write(x)
    f.write('\n')
    f.write(y)
    f.write('\n')
    f.write(z)
    f.write('\n')
    f.write(a)
    f.write('\n')
    f.write(b)
    f.write('\n')
    f.write(c)
    f.write('\n')
    f.write(d)
    f.write('\n')
    f.write(e)
    f.write('\n')
    f.write(u)
    f.write('\n')
    f.write(g)


    